[package]
name = "tiltify-twitchbot"
version = "0.3.0"
edition = "2024"

[dependencies]
thiserror = { version = "2.0.12", features = [] }
axum = { version = "0.8.4", features = ["http2", "json", "tracing", "tokio", "matched-path", "default", "macros"] }
axum-extra = { version = "0.12.6", features = ["typed-header"] }
eyre = "0.6.12"
dotenvy = { version = "0.15.7", features = ["clap"] }
serde = { version = "1.0.219", features = ["derive", "alloc"] }
serde_json = { version = "1.0.140", features = [] }
tokio = { version = "1.44.2", default-features = false, features = ["rt", "rt-multi-thread", "macros", "signal"] }
tokio-stream = { version = "0.1.18", features = ["sync"] }
headers = { version = "0.4.1", features = [] }
twitch_api = { version = "0.7.2", features = ["eventsub", "helix", "reqwest", "twitch_oauth2", "serde_json", "trace_unknown_fields", "tracing", ] }
twitch_oauth2 = { version = "0.15.2", features = ["client"] }
toml = "1.1.2+spec-1.1.0"
serde_derive = "1.0.219"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "serde"] }
reqwest = { version = "0.12.15", features = ["rustls-tls", "json", "stream"] }
sentry = { version = "0.48.0", features = ["tracing", "logs", "opentelemetry"] }
chrono = { version = "0.4.44", features = ["serde"] }
tower-http = { version = "0.6.8", features = ["fs", "trace"] }
oauth2 = { version = "5.0.0", features = [] }
futures-util = { version = "0.3.32", default-features = false, features = ["sink", "std"] }

[profile.release]
opt-level = 3
debug = true